#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $SATYA_REPO == "SATYA-SPAM-BOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0RFQURMWS1GSUdIVEVSUy9ERUFETFktU1BBTS1CT1QvYXJjaGl2ZS9tYWluLnppcA==" | base64 -d
    elif [[ $SATYA_REPO == "SATYA-SPAM-BOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0RFQURMWS1GSUdIVEVSUy9ERUFETFktU1BBTS1CT1QvYXJjaGl2ZS9tYWluLnppcA==" | base64 -d
    elif [[ $SATYA_REPO =~ $regex ]]
    then
        if [[ $SATYA_REPO_BRANCH ]]
        then
            echo "${SATYA_REPO}/archive/${SATYA_REPO_BRANCH}.zip"
        else
            echo "${SATYA_REPO}/archive/satya.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0RFQURMWS1GSUdIVEVSUy9ERUFETFktU1BBTS1CT1QvYXJjaGl2ZS9tYWluLnppcA==" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="satya-spam-bot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    SATYAPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $SATYAPATH
    echo "  Starting.  SATYA SPAM BOT "
    echo "SATYA SPAM BOT"

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m satyaspammer
}

_set_bot
